# Generated by Django 4.2.11 on 2024-04-16 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("RUC", "RUC"),
                            ("PASSPORT", "Passport"),
                        ],
                        default="DNI",
                        help_text="Customer document type",
                        max_length=9,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        help_text="Customer document number", max_length=15
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Customer birth date", null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="Customer phone number", max_length=10),
                ),
                (
                    "address",
                    models.CharField(help_text="Customer address", max_length=100),
                ),
                (
                    "cci",
                    models.CharField(
                        blank=True,
                        help_text="Customer CCI number",
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Customer bank name",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("BUYER", "Buyer"), ("SELLER", "Seller")],
                        default="BUYER",
                        help_text="Customer type",
                        max_length=6,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Auction ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Product name", max_length=100)),
                ("description", models.TextField(help_text="Product description")),
                (
                    "starting_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Starting price", max_digits=10
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Final price", max_digits=10
                    ),
                ),
                ("start_date", models.DateTimeField(help_text="Auction start date")),
                ("end_date", models.DateTimeField(help_text="Auction end date")),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Auction seller",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions_sold",
                        to="core.customer",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auction winner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions_won",
                        to="core.customer",
                    ),
                ),
            ],
        ),
    ]
