# Generated by Django 4.2.11 on 2024-04-19 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Bid ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Bid amount", max_digits=10
                    ),
                ),
                ("date", models.DateTimeField(help_text="Bid date")),
                (
                    "auction",
                    models.ForeignKey(
                        help_text="Auction bid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.auction",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer bid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                    ),
                ),
            ],
        ),
    ]
