# Generated by Django 4.2.11 on 2024-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="date",
            field=models.DateTimeField(auto_now_add=True, help_text="Bid date"),
        ),
    ]
