# Generated by Django 4.2.11 on 2024-05-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_bid_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="validated_email",
            field=models.BooleanField(
                default=False, help_text="Customer email validation"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="validated_phone",
            field=models.BooleanField(
                default=False, help_text="Customer phone validation"
            ),
        ),
    ]
