# Generated by Django 4.2.11 on 2024-06-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customer_validated_email_customer_validated_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="verification_code",
            field=models.CharField(
                blank=True,
                help_text="Customer verification code",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="verification_code_expiry",
            field=models.DateTimeField(
                blank=True, help_text="Customer verification code expiry", null=True
            ),
        ),
    ]
