# Generated by Django 4.2.11 on 2024-06-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customer_verification_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Product image", null=True, upload_to="auctions/"
            ),
        ),
    ]
