# Generated by Django 4.2.11 on 2024-06-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
    ]
