# Generated by Django 4.2.11 on 2024-06-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_customer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Product image", null=True, upload_to="auctions/"
            ),
        ),
    ]
