# Generated by Django 4.2.11 on 2024-06-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='categoy',
            field=models.CharField(blank=True, help_text='Product category', max_length=50),
        ),
    ]
