# Generated by Django 4.2.11 on 2024-06-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='estado',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Estado del objeto'),
        ),
    ]
