# Generated by Django 4.2.11 on 2024-07-01 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_auction_image_auction_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Auction winner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions_won', to='core.customer'),
        ),
    ]
