# Generated by Django 4.2.11 on 2024-06-26 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auction_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Auction image', upload_to='auctions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Image upload date')),
                ('auction', models.ForeignKey(help_text='Auction image', on_delete=django.db.models.deletion.CASCADE, to='core.auction')),
            ],
        ),
    ]
