# Generated by Django 4.2.11 on 2024-07-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_auction_winner'),
    ]

    operations = [
    ]
